### ISSUE TITLE
document minimum IAM roles

### ISSUE THREAD

**Issue by eeaton** [GoogleCloudPlatform/mqtt-cloud-pubsub-connector#16]
It looks like the MQTT client assumes the default compute service account with Editor roles. To avoid relying on the default editor privileges for the service account and default project owner for the user, please consider the revisions below:

1. **terraform/gke.tf** : for the MQTT client, specify a service account with the minimum IAM roles explicitly declared 
2. **/readme.md**: for the user identity running the scripts in this repo, specify the minimum IAM roles they'll need to invoke resource creation for GKE / pubsub etc

**Comment by ferrarimarco** [comment]
Hi!

> It looks like the MQTT client assumes the default compute service account with Editor roles. To avoid relying on the default editor privileges for the service account and default project owner for the user, please consider the revisions below:
> 
> 1. **terraform/gke.tf** : for the MQTT client, specify a service account with the minimum IAM roles explicitly declared

I enabled workload identity, and set it to only have the `roles/pubsub.publisher` role. The connector then uses a Kubernetes service account that the deployment script [dynamically maps](https://github.com/GoogleCloudPlatform/mqtt-cloud-pubsub-connector/blob/main/scripts/deploy-workloads.sh#L148) to the Google Cloud service account created by the the workload-idenenty module (see the relevant output definition [here](https://github.com/GoogleCloudPlatform/mqtt-cloud-pubsub-connector/blob/main/terraform/outputs.tf#L72).

> 2. **/readme.md**: for the user identity running the scripts in this repo, specify the minimum IAM roles they'll need to invoke resource creation for GKE / pubsub etc

True, this information is missing. I'll address it in https://github.com/GoogleCloudPlatform/mqtt-cloud-pubsub-connector/blob/main/docs/provision-deploy-google-cloud-gke.md
