### ISSUE TITLE
MQTT Publish topic as an attribute of the Pub/Sub message

### ISSUE THREAD

**Issue by r-harrison** [GoogleCloudPlatform/mqtt-cloud-pubsub-connector#201]
Hi,

Is it possible to capture the topic that the MQTT message came through, and add as an attribute of the resulting GCP Pub/Sub message?

**Comment by ferrarimarco** [comment]
Hi @r-harrison !

What is your use case here? Are you using a wildcard MQTT subscription?

**Comment by r-harrison** [comment]
Hi @ferrarimarco :-)

My apologies, I should have included our use case in my original request - yes, we are using a wildcard subscription. Unfortunately the topic name conveys information about the structure of the resulting payload, which makes deserialisation on the other end cumbersome without that extra context.

I've had a look at the code and think that something like this might do the trick (line 85 of MqttToCloudPubSubRoute.java):

` from(routeStart)
        .id(mqttToCloudPubSubRouteId)
        .process(
            exchange -> {
              String mqttTopic =
                  exchange.getIn().getHeader("CamelMQTTSubscribeTopic", String.class);
              exchange.getIn().setHeader("CamelGooglePubsubAttributes", "mqtt_topic=" + mqttTopic);
            })
        .to(routeDestination);`

I haven't written any tests for the above yet but I'm happy to throw up a PR if you are amenable (noting that your non-goals included mapping of MQTT semantics to Pub/Sub).

**Comment by ferrarimarco** [comment]
I'd be happy to review a PR for this! Thanks :)

**Comment by ferrarimarco** [comment]
@r-harrison: I've opened #290 to implement this feature request. Can you kindly check if it's what you're looking for? Thanks!

**Comment by r-harrison** [comment]
This is perfect, thanks mate :)
